### ISSUE TITLE
Shape of data in price.csv, msg.csv, ORDER.csv

### ISSUE THREAD

**Issue by mogaoga** [imTurkey/Market-Making-with-Deep-Reinforcement-Learning-from-Limit-Order-Books#1]
Thank you for sharing your wonderful ideas. 
I have a question. Could you please show me what price.csv, msg.csv, ORDER.csv, and TRADE.csv look like? 
Even if it's just a partial view, I would appreciate seeing them.

**Comment by imTurkey** [comment]
Hey, thanks for your interests.
The "price.csv" is used to save price information during backtesting, it's used for the convenience of the simulator. Its table header includes:

timestamp,ask1_price,bid1_price,midprice,spread,last_price,trading_price,trading_volume

And "msg.csv" is used for calculating Order Strength Index (OSI) in III-A section, its table header includes:

timestamp,market_buy_volume,market_buy_n,market_sell_volume,market_sell_n,limit_buy_volume,limit_buy_n,limit_sell_volume,limit_sell_n,withdraw_buy_volume,withdraw_buy_n,withdraw_sell_volume,withdraw_sell_n

ORDER.csv and TRADE.csv includes raw information from the Exchange, ORDER includes

Symbol,TradingDate,TradingTime,SetID,RecID,OrderPrice,OrderVolume,OrderType,UNIX,Market,SymbolSource,OrderCode,SecurityID

TRADE includes

Symbol,TradingDate,TradingTime,BuyOrderID,SellOrderID,TradePrice,TradeVolume,TradeType,UNIX,Market,SecurityID,SymbolSource,SetID,RecID

The ask/bid/price/msg files are artifacts during the LOB reconstruction, they are used to save the essential information for subsequent calculation. Anyway, different data source may result in different data shapes, but the core data is similar. I hope you found that helpful.

**Comment by mogaoga** [comment]
Thank you for your prompt response. 
It was very helpful and informative.
